
{-# OPTIONS -fglasgow-exts -XForeignFunctionInterface #-}
module HS_CURAND_H_S_n (
  module HS_CURAND_H_S_n
) where

import Foreign
import Foreign.C.Types

newtype S_CUevent_st = S_CUevent_st ()
newtype S_CUstream_st = S_CUstream_st ()
newtype S_CUuuid_st = S_CUuuid_st ()
newtype S_char1 = S_char1 ()
newtype S_char2 = S_char2 ()
newtype S_char3 = S_char3 ()
newtype S_char4 = S_char4 ()
newtype S_cudaArray = S_cudaArray ()
newtype S_cudaChannelFormatDesc = S_cudaChannelFormatDesc ()
newtype S_cudaDeviceProp = S_cudaDeviceProp ()
newtype S_cudaExtent = S_cudaExtent ()
newtype S_cudaFuncAttributes = S_cudaFuncAttributes ()
newtype S_cudaGraphicsResource = S_cudaGraphicsResource ()
newtype S_cudaMemcpy3DParms = S_cudaMemcpy3DParms ()
newtype S_cudaPitchedPtr = S_cudaPitchedPtr ()
newtype S_cudaPos = S_cudaPos ()
newtype S_curandGenerator_st = S_curandGenerator_st ()
newtype S_dim3 = S_dim3 ()
newtype S_double1 = S_double1 ()
newtype S_double2 = S_double2 ()
newtype S_double3 = S_double3 ()
newtype S_double4 = S_double4 ()
newtype S_float1 = S_float1 ()
newtype S_float2 = S_float2 ()
newtype S_float3 = S_float3 ()
newtype S_float4 = S_float4 ()
newtype S_int1 = S_int1 ()
newtype S_int2 = S_int2 ()
newtype S_int3 = S_int3 ()
newtype S_int4 = S_int4 ()
newtype S_long1 = S_long1 ()
newtype S_long2 = S_long2 ()
newtype S_long3 = S_long3 ()
newtype S_long4 = S_long4 ()
newtype S_longlong1 = S_longlong1 ()
newtype S_longlong2 = S_longlong2 ()
newtype S_longlong3 = S_longlong3 ()
newtype S_longlong4 = S_longlong4 ()
newtype S_short1 = S_short1 ()
newtype S_short2 = S_short2 ()
newtype S_short3 = S_short3 ()
newtype S_short4 = S_short4 ()
newtype S_surfaceReference = S_surfaceReference ()
newtype S_textureReference = S_textureReference ()
newtype S_uchar1 = S_uchar1 ()
newtype S_uchar2 = S_uchar2 ()
newtype S_uchar3 = S_uchar3 ()
newtype S_uchar4 = S_uchar4 ()
newtype S_uint1 = S_uint1 ()
newtype S_uint2 = S_uint2 ()
newtype S_uint3 = S_uint3 ()
newtype S_uint4 = S_uint4 ()
newtype S_ulong1 = S_ulong1 ()
newtype S_ulong2 = S_ulong2 ()
newtype S_ulong3 = S_ulong3 ()
newtype S_ulong4 = S_ulong4 ()
newtype S_ulonglong1 = S_ulonglong1 ()
newtype S_ulonglong2 = S_ulonglong2 ()
newtype S_ulonglong3 = S_ulonglong3 ()
newtype S_ulonglong4 = S_ulonglong4 ()
newtype S_ushort1 = S_ushort1 ()
newtype S_ushort2 = S_ushort2 ()
newtype S_ushort3 = S_ushort3 ()
newtype S_ushort4 = S_ushort4 ()

